### ISSUE TITLE
Unable to batch opencerts schema 2.0 certificate

### ISSUE THREAD

**Issue by laykoonjune** [GovTechSG/certificate-application#129]
Hi, 

I unable to batch opencerts schema 2.0 certificate, is giving me error invalid documents. 
Is there anything missing that i need to do?+
![Capture](https://user-images.githubusercontent.com/46921398/74923791-5d4eaf80-540c-11ea-9648-a034f85128d1.PNG)

**Comment by Nebulis** [comment]
Please share your document

**Comment by laykoonjune** [comment]
[MCPDC_test.txt](https://github.com/OpenCerts/certificate-cli/files/4233652/MCPDC_test.txt)
I have change the file format to .txt instead of .opencerts as github does not allow .opencert file.

**Comment by Nebulis** [comment]
I just pushed a fix => https://github.com/OpenCerts/certificate-cli/commit/2da9e33a5ce6183b2b48973458ee07209ddf722b

You can update your git repo and run the command again, it should work (the schema version was not correct). Let me know if it works.

On a side note, you shouldn't use openattestation.com for the identity proof => you should use your domain

**Comment by laykoonjune** [comment]
I try to update and re run and is still not working. Please advice. 

Noted one the identity proof and have made the necessary changes. thanks

**Comment by laykoonjune** [comment]
I try to make the changes of the version manually I'm able to batch the certificate. not sure why git pull did not update the file.

**Comment by laykoonjune** [comment]
[Signed MCPDC_test.txt](https://github.com/OpenCerts/certificate-cli/files/4234578/Signed.MCPDC_test.txt)
I have attached my signed certs it looks a bit weird. it does not have any proof and the target hash and merkle root is the same
 
Also, can I check where can I verify my certificate to ensure my certificate renderer is working in the test network. Currently there doesn't seems to have any network selection in opencerts.io

**Comment by Nebulis** [comment]
You can test your certificate in dev.opencerts.io

if you wrap only one document, there will be no prrof, and targethash and merkle root will be the same

**Comment by laykoonjune** [comment]
Noted with thanks.

**Comment by laykoonjune** [comment]
Sorry to disturb you again.
I am trying to issue new certificate but can't seems to be able to do so do you have any idea why. 
The issue button will change to issuing and change back to issue without prompting any deduction on my test ethers account.

**Comment by Nebulis** [comment]
Hard to say, you can open the console and see if any error happens (like gas limit exceeded). Common mistakes are:
- wrong document store
- not enough ethers
- wrong network

**Comment by laykoonjune** [comment]
![image](https://user-images.githubusercontent.com/46921398/75128086-6934bd00-56fd-11ea-8db2-661d890ced85.png)
Just as you expected the error is gas limit exceeded

**Comment by Nebulis** [comment]
Did you check all the above ?
- make sure you are using the correct document store with the correct wallet
- make sure you are using the correct network

I can see that the address https://ropsten.etherscan.io/address/0x5f007251c78cA92d3053492cCf0EDC161063624c has been created by the wallet https://ropsten.etherscan.io/address/0xe768079b364121bb09513db502e7f815f3f31800

Is this correct ?

**Comment by laykoonjune** [comment]
The wallet is the old wallet which i am unable to import back to my metamask. is it possible to link the new wallet back to the same document store?

**Comment by Nebulis** [comment]
If you are not able to connect to your old wallet it's not possible. You need to deploy a new wallet from your new wallet

**Comment by laykoonjune** [comment]
Do I need to update the legacy registry again or I just need to add in my DNS TXT record?

**Comment by Nebulis** [comment]
it depends, if you want to be able to display that you are in the registry on dev.opencerts.io you can open a new MR to update the address

Otherwise just using the DNS-TXT is enough to test and render document

**Comment by laykoonjune** [comment]
Is there a process how i can go about to raise the MR? thanks.

**Comment by Nebulis** [comment]
follow github fork process https://help.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by laykoonjune** [comment]
Thanks for your help.
